KoRequireMVCSample/Controllers/ProductController.cs
using KnockoutMVCApplication.ProductImage.Command.AddProductImageCommand;
using KnockoutMVCApplication.ProductImage.Model;
using KoRequireMVCSample.Factory;
using KoRequireMVCSample.Models;
using System;
using System.Web.Mvc;

namespace KoRequireMVCSample.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductViewModelFactory productViewModelFactory;
        private readonly IAddProductImageCommand addProductImageCommand;

        public ProductController(IProductViewModelFactory productViewModelFactory, IAddProductImageCommand addProductImageCommand)
        {
            this.productViewModelFactory = productViewModelFactory;
            this.addProductImageCommand = addProductImageCommand;
        }

        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        [Route("InitializeData")]
        [HttpGet]
        public ActionResult InitializeData()
        {
            var vm = productViewModelFactory.CreateProductViewModel();

            return Json(vm, JsonRequestBehavior.AllowGet);
        }

        //[Route("SaveProductImage")]
        //[HttpPost]
        //public ActionResult SaveProductImage(AddProductImageModel addProductImageModel)
        //{
        //    var vm = addProductImageCommand.ExecuteAddProductImage(addProductImageModel);

        //    return Json(vm, JsonRequestBehavior.AllowGet);
        //}


        [Route("SaveProductImage")]
        [HttpPost]
        public ActionResult SaveProductImage(AddProductWithImageModel addProductImageModel)
        {
            AddProductImageModel addProductImageModelApplication = new AddProductImageModel();
            addProductImageModelApplication.id = addProductImageModel.id;
            addProductImageModelApplication.Description = addProductImageModel.Description;
            addProductImageModelApplication.ProductId = addProductImageModel.ProductId;

            addProductImageModelApplication.Image = Convert.FromBase64String(addProductImageModel.Image);

            var vm = addProductImageCommand.ExecuteAddProductImage(addProductImageModelApplication);

            return Json(vm, JsonRequestBehavior.AllowGet);
        }

        [Route("UploadImage")]
        [HttpPost]
        public void UploadImage(string imageData)
        {
            Console.WriteLine(imageData);
        }
    }
}

KoRequireMVCSample/Controllers/ProductImagesController.cs
using KnockoutMVCApplication.ProductImage.Model;
using KnockoutMVCApplication.ProductImage.Query.GetProductImageQuery;
using KoRequireMVCSample.Factory;
using KoRequireMVCSample.Models.ViewModels;
using System.Web.Mvc;

namespace KoRequireMVCSample.Controllers
{
    [Authorize]
    public class ProductImagesController : Controller
    {
        IProductImageViewModelFactory ProductImageViewModelFactory;
        IEditProductImageViewModelFactory editProductImageViewModelFactory;
        IGetProductImageQuery getProductImageQuery;

        public ProductImagesController(IProductImageViewModelFactory ProductImageViewModelFactory, 
                                       IEditProductImageViewModelFactory editProductImageViewModelFactory,
                                       IGetProductImageQuery getProductImageQuery)
        {
            this.ProductImageViewModelFactory = ProductImageViewModelFactory;
            this.editProductImageViewModelFactory = editProductImageViewModelFactory;
            this.getProductImageQuery = getProductImageQuery;
        }
        // GET: ProductImages
        public ActionResult Index()
        {
            return View();
        }

        [Route("InitializeData")]
        [HttpGet]
        public ActionResult InitializeData()
        {
            var vm = ProductImageViewModelFactory.CreateProductImagesViewModel();

            return Json(vm.ProductImageLists, JsonRequestBehavior.AllowGet);
        }

        [Route("Get64ByteString")]
        [HttpGet]
        public ActionResult GetImage64ByteString(int id)
        {
            ProductImageDetailModel vm = getProductImageQuery.ExecuteQuery(id);

            return Json(vm, JsonRequestBehavior.AllowGet);
        }
    }
}

KoRequireMVCSample/Controllers/ProductTypeController.cs
using KnockoutMVCApplication.ProductType;
using KnockoutMVCApplication.ProductType.AddProductTypeCommand;
using KnockoutMVCApplication.ProductType.AddProductTypeCommand.Model;
using KnockoutMVCApplication.ProductType.DeleteProductTypeCommand;
using KnockoutMVCApplication.ProductType.GetViaIdProductTypesQuery;
using KnockoutMVCApplication.ProductType.UpdateProductTypesCommand;
using KoRequireMVCSample.Factory;
using System.Web.Mvc;

namespace KoRequireMVCSample.Controllers
{
    [Authorize]
    public class ProductTypeController : Controller
    {
        private readonly IProductTypeViewModelFactory productTypeViewModelFactory;
        private readonly IAddProductTypeCommand addProductTypeCommand;
        private readonly IDeleteProductTypeCommand deleteProductTypeCommand;
        private readonly IUpdateProductTypesCommand updateProductTypesCommand;
        public ProductTypeController(IProductTypeViewModelFactory productTypeViewModelFactory, IAddProductTypeCommand addProductTypeCommand,
                                     IDeleteProductTypeCommand deleteProductTypeCommand, IUpdateProductTypesCommand updateProductTypesCommand)
        {
            this.productTypeViewModelFactory = productTypeViewModelFactory;
            this.addProductTypeCommand = addProductTypeCommand;
            this.deleteProductTypeCommand = deleteProductTypeCommand;
            this.updateProductTypesCommand = updateProductTypesCommand;
        }
        // GET: ProductType
        public ActionResult Index()
        {
            return View();
        }

        [Route("InitializeData")]
        [HttpGet]
        public ActionResult InitializeData()
        {
            var vm = productTypeViewModelFactory.CreateProductTypeViewModel();

            return Json(vm, JsonRequestBehavior.AllowGet);
        }

        [Route("AddProductType")]
        [HttpPost]
        public JsonResult AddProductType(AddProductTypeModel addProductTypeModel)
        {
            var vm = "";
            addProductTypeCommand.ExecuteCommand(addProductTypeModel);
            return Json(vm, JsonRequestBehavior.AllowGet);
        }

        [Route("DeleteProductType")]
        [HttpGet]
        public ActionResult DeleteProductType(int id)
        {
            var vm = "";
            deleteProductTypeCommand.ExecuteCommand(id);
            return Json(vm, JsonRequestBehavior.AllowGet);
        }

        [Route("UpdateProductType")]
        [HttpPost]
        public ActionResult UpdateProductType(ProductTypeDetailModel productTypeDetailModel)
        {
            var vm = "";
            updateProductTypesCommand.ExecuteCommand(productTypeDetailModel);
            return Json(vm, JsonRequestBehavior.AllowGet);
        }
    }
}

KoRequireMVCSample/Views/Shared/_Layout.cshtml
@using KoRequireMVCSample.Extensions;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Scripts.Render("~/bundles/EssentialScripts")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")


    <script>var version = "@Html.AssemblyRevisionNumber()";</script>
</head>
<body>
    <div class="container">
        <div class="row">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                @Html.ActionLink("Inventory Sales Management", "Index", "Home",
                                 new { area = "" }, new { @class = "navbar-brand" })
                <div class="collapse navbar-collapse" id="navbarNav">
                    <div class="navbar-nav">
                        @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-item nav-link" })
                        @Html.ActionLink("Product Editor", "Index", "Product", new { area = "" }, new { @class = "nav-item nav-link" })
                        @Html.ActionLink("Product Type Editor", "Index", "ProductType", new { area = "" }, new { @class = "nav-item nav-link" })
                        @Html.ActionLink("Product Image Editor", "Index", "ProductImages", new { area = "" }, new { @class = "nav-item nav-link" })

                        @Html.Partial("_LoginPartial")
                    </div>
                  
                </div>

            </nav>
        </div>
        <div class="row">
            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Using Require.js, Knockout and MVC</p>
                </footer>
            </div>
        </div>
       
    </div>
    <script src="@Html.ScriptsPath("lib/require.js")"></script>
    @RenderSection("scripts", required: false)

</body>
</html>